CREATE TABLE servers (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  ip VARCHAR(20) NOT NULL,
  created_by VARCHAR(36) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_by VARCHAR(36) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);